In [36]:
import numpy as np
import pandas as pd
import re,math
from sklearn import preprocessing
from scipy.stats import pearsonr
import matplotlib.pyplot as plt



data1 = pd.read_csv(r'2022_02_23_07_33_27.csv',encoding='gbk')
data2 = pd.read_excel(r'选择你所在家乡城市 描述统计.xlsx')
data3 = pd.read_excel(r'学校以及学院 描述统计.xlsx')
data4 = pd.read_excel(r'W020211027623974108131.xls')
data5 = pd.read_excel(r'中国一二三四五线城市名单.xlsx')
data6 = pd.read_excel(r'中国大学专业学科.xlsx')

In [37]:
# 去空
for i in range(len(data4)):
    if pd.isnull(data4["Unnamed: 5"][i]):
        data4 = data4.drop(i)

In [38]:
data4

      附件1：  Unnamed: 1  Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6
1       序号        学校名称       学校标识码       主管部门        所在地       办学层次         备注
3        1        北京大学  4111010001        教育部        北京市         本科        NaN
4        2      中国人民大学  4111010002        教育部        北京市         本科        NaN
5        3        清华大学  4111010003        教育部        北京市         本科        NaN
6        4      北京交通大学  4111010004        教育部        北京市         本科        NaN
...    ...         ...         ...        ...        ...        ...        ...
2784  2752   阿勒泰职业技术学院  4165014680   新疆维吾尔自治区      阿勒泰地区         专科        NaN
2785  2753    塔城职业技术学院  4165014740   新疆维吾尔自治区       塔城地区         专科        NaN
2786  2754   塔里木职业技术学院  4165014741   新疆生产建设兵团       阿拉尔市         专科        NaN
2787  2755  新疆工业职业技术学院  4265051060   新疆维吾尔自治区      乌鲁木齐市         专科        NaN
2788  2756   铁门关职业技术学院  4165014660   新疆生产建设兵团       铁门关市         专科        NaN

[2757 rows x 7 columns]

In [39]:
data3

               类别  频次     百分数
0          吉林师范大学   4  0.0067
1    陕西师范大学生命科学学院   3  0.0050
2          华南师范大学   2  0.0033
3        河南护理职业学院   2  0.0033
4          四川师范大学   2  0.0033
..            ...  ..     ...
565  中南大学交通运输工程学院   1  0.0017
566    苏州科技大学人文学院   1  0.0017
567  北京交通大学交通运输学院   1  0.0017
568   广东药科大学医药商学院   1  0.0017
569       华威大学商学院   1  0.0017

[570 rows x 3 columns]

In [40]:
bkyx = np.array(data4[data4["Unnamed: 5"] == "本科"]["Unnamed: 1"])
zkyx = np.array(data4[data4["Unnamed: 5"] == "专科"]["Unnamed: 1"])
bkyx

array(['北京大学', '中国人民大学', '清华大学', ..., '新疆科技学院', '新疆政法学院', '新疆天山职业技术大学'],
      dtype=object)

In [41]:
bktemp = []
zktemp = []
errotemp = []
for index, row in data3.iterrows():
    tp = row["类别"].split("大学")[0] + "大学"
    if tp in bkyx:
        bktemp.append(np.array(row))
    elif tp in zkyx:
        zktemp.append(np.array(row))
    else:
        errotemp.append(np.array(row))

In [42]:
for i,j in zip([errotemp, bktemp, zktemp],["未识别大学", "本科大学", "专科大学"]):
    pd.DataFrame(i, columns=data3.columns).to_csv(f"./大学描述/{j}.csv",encoding="utf_8_sig")

In [43]:
tpc = data5.copy()
tem = np.array(data5["城市链接"])
temp = []
temp2 = []
for i in tem:
    if len(i.split("：")) == 2:
        temp.append(i.split("：")[1])
        temp2.append(i.split("：")[0])
    else:
        temp.append(i)
        temp2.append(i)
tpc["城市链接"] = pd.DataFrame(temp)
tpc = pd.concat([tpc, pd.DataFrame(temp2)], axis=1).drop(["Unnamed: 6", "Unnamed: 4", "全国共计337个地级以上城市（2019年5月）：" ], axis=1)
yxcity = np.array(tpc[tpc["城市分级"] == "一线城市"]["城市链接"])
xyxcity = np.array(tpc[tpc["城市分级"] == "新一线城市"]["城市链接"])
erxcity = np.array(tpc[tpc["城市分级"] == "二线城市"]["城市链接"])
sanxcity = np.array(tpc[tpc["城市分级"] == "三线城市"]["城市链接"])
sixcity = np.array(tpc[tpc["城市分级"] == "四线城市"]["城市链接"])
wuxcity = np.array(tpc[tpc["城市分级"] == "五线城市"]["城市链接"])

In [44]:
yxtemp = []
xyxtemp = []
erxtemp = []
sanxtemp = []
sixtemp = []
wuxtemp = []
errotemp = []
for index, row in data2.iterrows():
    tp1 = row["类别"].split("，")[0]
    tp2 = row["类别"].split("，")[1]
    if tp2 in yxcity:
        yxtemp.append(np.array(row))
    elif tp2 in xyxcity:
        xyxtemp.append(np.array(row))
    elif tp2 in erxcity:
        erxtemp.append(np.array(row))
    elif tp2 in sanxcity:
        sanxtemp.append(np.array(row))
    elif tp2 in sixcity:
        sixtemp.append(np.array(row))
    elif tp2 in wuxcity:
        wuxtemp.append(np.array(row))
    else:
        errotemp.append(np.array(row))

In [45]:
data1["学校以及学院"]

0                Q2
1            豫章师范学院
2          厦门大学经济学院
3           上海大学医学院
4        吉林大学珠海科技学院
           ...
596    太原理工大学现代科技学院
597      湖北黄冈应急管理学院
598          山东女子学院
599          中国人民大学
600          浙江师范大学
Name: 学校以及学院, Length: 601, dtype: object

In [46]:
bktemp = []
zktemp = []
errotemp = []
for index, row in data1.iterrows():
    tp = row["学校以及学院"].split("大学")[0] + "大学"
    try:
        tp1 = row["学校以及学院"].split("大学")[1]
    except:
        tp1 = ""
    if tp in bkyx:
        bktemp.append(np.array(row))
    elif tp in zkyx:
        zktemp.append(np.array(row))
    else:
        errotemp.append(np.array(row))
for i,j in zip([errotemp, bktemp, zktemp],["未识别大学", "本科大学", "专科大学"]):
    pd.DataFrame(i, columns=data1.columns).to_csv(f"./具体问卷/{j}.csv",encoding="utf_8_sig")

In [47]:
yxtemp1 = []
xyxtemp1 = []
erxtemp1 = []
sanxtemp1 = []
sixtemp1 = []
wuxtemp1 = []
errotemp1 = []
for index, row in data1.iterrows():
#     tp1 = row["类别"].split("，")[0]
#     tp2 = row["类别"].split("，")[1]
    tp2 = row["城市"]
    if tp2 in yxcity:
        yxtemp1.append(np.array(row))
    elif tp2 in xyxcity:
        xyxtemp1.append(np.array(row))
    elif tp2 in erxcity:
        erxtemp1.append(np.array(row))
    elif tp2 in sanxcity:
        sanxtemp1.append(np.array(row))
    elif tp2 in sixcity:
        sixtemp1.append(np.array(row))
    elif tp2 in wuxcity:
        wuxtemp1.append(np.array(row))
    else:
        errotemp1.append(np.array(row))
for i,j in zip([yxtemp1, xyxtemp1, erxtemp1, sanxtemp1, sixtemp1, wuxtemp1, errotemp1],["一", "新一", "二","三","四","五","误"]):
    pd.DataFrame(i, columns=data1.columns).to_csv(f"./具体问卷/{j}.csv",encoding="utf_8_sig")

In [61]:
temp_z = []
for i in range(1,4):
    temp_z.append(np.array(data6[data6["subject_tyle_level"] == i]["subject_name"]))

In [64]:
tp1_e = []
tp1_1 = []
tp1_2 = []
tp1_3 = []
for index, row in data1.iterrows():
    try:
        tp1 = row["学校以及学院"].split("大学")[1]
    except:
        tp1 = "无"
    if tp1 in temp_z[0]:
        tp1_1.append(row)
    elif tp1 in temp_z[1]:
        tp1_1.append(row)
    elif tp1 in temp_z[2]:
        tp1_1.append(row)
    else:
        print(tp1)
        tp1_e.append(row)
for i,j in zip([tp1_1, tp1_2, tp1_3, tp1_e],["1", "2", "3","无"]):
    pd.DataFrame(i, columns=data1.columns).to_csv(f"./具体问卷/专业{j}.csv",encoding="utf_8_sig")

无
无
经济学院
医学院
珠海科技学院

设计与艺术学院
计算机学院
软件学院
 生科
无
，国际经济与贸易
 理工实验班 心理学系
无
农业与生物技术学院

无
无
 传播学院
管理学院
无
港口与海岸工程学院

外国语学院
信息工程学院

工商管理学院
无
无
基础医学院
经管学院
天府学院
无

无
人文学院
无
金融学院
计算机学院
物理与电子电气工程学院
  机械与电气工程学院
无
数学与统计学院
，文学院
经济管理学院
物理科学学院
，教师教育学院
无


无
 信息工程学院
建筑学院
管理学院
文学院
心理学院
心理学部
 信息工程学院
机械与能源工程学院
 管理学院
 环境学院
西方语学院
生命科学学院
东昌学院  中文系
工商管理学院
无
生命科学学院

商学院
交通运输学院
 人文学院
无
物理与光电工程学院
无

无
心理学院
中山学院人文学院
无
外国语学院
教育科学学院
经济学院
 地理科学学院

法学院
外国语学院
生物医学工程学院
马院

法政学院
无
无
无
 香料香精化妆品学院
信息管理学院
无
管理学院
无
无
理学院
教育学院

无

无
朝汉文学院
物理与电子信息学院

管理学院
无
无
地理科学学院
无
体育学院
药学院
 民族学与社会学学院
电气工程学院
计算机学院
经济学院
信息工程学院
电子学院
无

地理与环境科学学院
基础医学院
无
  文化传媒学院
 数学科学学院
 化工食品学院
无
影视传媒学院
工商管理学院
无
 经济管理学院
公共管理学院
人文学院
无
劳动人事学院
理学院
资源与资源科学学院
 药学院
 教育学部
数理学院
 信息管理学院
职教学院
无
 工业工程系
无
无
 新闻与传播学院
 经管学院
经济学院
物理学院



锦江学院东坡学院
统计学院
 教育科学学院
中医药学院
外国语学院

无

无
 经济管理学院
金山学院
无
无
无


政法学院
无
针灸推拿学院
英语学院

艺传学院
无
环境与资源学院
   商学院
无
商学院
统计学院
航空运输学院
无

人文学院
无
经济管理学院

信息学院

无
无
 经理管理学院
 外国语
化工学院
经济管理学院
历史文化旅游学院
心理学部
音乐与录音艺术学院
无
经济管理学院
东北亚学院


无

管理学院
 新闻传播学院
机械工程学院
材料学院

无
无
师范学院
无

无
信息工程学院
 安全科学与工程学院
管理学院
自动化学院
物理科学与信息工程学院
公共经济与管理学院
外语学院
法学院
商学院
美术学院

经济学院
无
物理学院
无
化学学院
无
体育学院
无
护理学院
新闻传播学院
文学院
无
金融学院
交通学院
心理学院
，计算机科学与工程学院
医学部
管理学院
生命科学学院
 图像传播研究中心
法学院
外语学院
无
物理学院
口腔医学院
心理学院
旅游学院
无
传播科学与艺术学院
商学院
无
无

历史与档案学院
无
经济学院
计算机学院

无
无

食品与生物工程学院
电子与信息工程学院
无

计算机学院
经管学院
无
无
商务学院 会计学院
民商经济法学院
无
工商管理学院
信息科学与工程学院

无
商学院
-商学院

药学院
教育学院
无
经济学院
无
医学部
外国语言文化学院
无
无
无
 电气与自动化学院
机电学院
 国家治理学院
商学院
无
无
物理与天文学院
无
汇华学院
无
 电子信息与电气工程学院
管理学院
无
新闻传播学院
无
无
，经济学院
无
无
商学院
公共卫生与管理学院
交通运输工程学院
无
艺术学院
电气学院
管理学院
无
文学院
经济学院
生命科学学院

江河建筑学院
工学院
无
无
 信息学院
，康复医学院
无
计算机学院
政治与公共管理学院
无
，资环学院
无
无
 电子商务学院
临床医学院
无
无

法学院
基础医学院招生办
中山学院经管系
无


无
 交通运输工程学院
无


无
无

华商学院
经济管理学院
经管学院
无
无
科学技术学院  财经学科部
教师教育学院
无
无
医学院
无
法学院
机电学院
 材料科学与工程学院
物理与电子信息学院
生物系统工程与食品科学学院
无
政府管理学院
无
环境学院
管理学院
数计学院
无
无
公共管理学院
经济与金融学院
物理与机电工程学院
数学系
文学院
土木系
无
无
材料与能源学院
，机械工程学院
经济与贸易学院
无
经济与管理学院
管理学院
 机械工程学院
经理管理学院
信息资源管理学院
生科院

商务学院
 建筑工程
历史学院
文学院
媒体融合与传播国家重点实验室
，信网学院
无
无
文学院
建筑与城乡规划学院
   设计学院
经济学院
经济学院
智能科学与工程学院
无
经济学院
土木工程学院
文学院
无
无
 法学院
   数学与计算机科学学院
无
无
经济管理学院
无
管理学院
计算机科学学院

经济管理学院
无
历史文化学院
无
马克思主义学院
 动力与能源学院

无
无
无
外国语学院
岭南学院
新闻与传播学院
无
外国语学院
无

 管理学院
无
理工学院
历史文化学院
 教育学院
无
护理学院
音乐学院
化工学院
文学院
 管理学院
，音乐学院
地理科学与旅游学院
医学院
 外国语学院
无
信息技术学院
无
无
法学院
电子工程学院
物理系
医药商学院
无

资源工程
无
动物科技学院
民族学与社会学学院
无
-东北亚学院
 经济学院
无
  经管学院
经济与管理学院
土木工程学院
工程学院
文学院

材料学院
衡阳医学院
无
无
公共管理学院
金融学院
法学院
经济学院
环境学院
 机械与电气工程学院
无
化学化工学院
商学院
法学院
生命科学学院
国传学院
无
园林学院
哲学学院
 英语语言文学
无
 学前教育学院
计算机科学与工程学院
无
无
汽车工程学院
教育学部
土木工程学院
 软件工程
法学院
 工商管理
管理学院
无
商学院
教育学院
化工学院
商学院
艺术学院
 物理与光电工程学院
无
 文学院
 电子信息与自动化学院
，生命科学学院
无
交通学院
历史文化学院
经济学院
纺织服装学院
无
工业工程系
无
无
   电气与信息工程学院

无
兽医学院
无
无
石油与化工学院

会计学院
经济管理学院
公共卫生学院

无
管理与科学学院
会计学院
新闻传播学院
中山学院人文学院
材料工程学院
文学院
经济学院
商学院
教育学院
会计学院
无
物院
无
英文学院
眼视光学院

无
无

整合医学学院
工商管理学院


光华管理学院
 数学学院
化学学院
无

外国语学院
 民族学与社会学学院
无
 农学院
无

文学院
化学学院

传媒学院
商学院
现代科技学院
无
无